---
name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
            packages: ''

      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build Moonlight
        uses: burrunan/gradle-cache-action@v3
        with:
          arguments: assembleNonRoot

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 -d > /tmp/debug.keystore

      - name: Sign APK With Key
        run: |
          jarsigner -verbose \
          -keystore /tmp/debug.keystore \
          -storepass android \
          -keypass android  \
          -signedjar ./app/build/outputs/apk/nonRoot/release/app-nonRoot-release-debugsigned.apk \
          ./app/build/outputs/apk/nonRoot/release/app-nonRoot-release-unsigned.apk \
          androiddebugkey

      - name: Align APK
        run: |
          $ANDROID_HOME/build-tools/34.0.0/zipalign -v 4 \
          ./app/build/outputs/apk/nonRoot/release/app-nonRoot-release-debugsigned.apk \
          ./app/build/outputs/apk/nonRoot/release/app-nonRoot-release.apk

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: moonlight-android.apk
          path: ./app/build/outputs/apk/nonRoot/release/app-nonRoot-release.apk
