---
name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'corretto'

      - uses: android-actions/setup-android@v3
        with:
            packages: ''

      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      # - name: Build artifact
      #   run: ./gradlew assembleNonRoot

      - uses: burrunan/gradle-cache-action@v3
        name: Build Moonlight
        with:
          arguments: assembleNonRoot

      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 -d > /tmp/debug.keystore

      - name: Debug sign
        run: | 
          jarsigner -verbose -keystore /tmp/debug.keystore -storepass android -keypass android  \ 
          -signedjar ./app/build/outputs/apk/nonRoot/release/app-nonRoot-release-debugsigned.apk ./app/build/outputs/apk/nonRoot/release/app-nonRoot-release-unsigned.apk \
          androiddebugkey

      - name: Align APK
        run: |
          $ANDROID_HOME/build-tools/34.0.0/zipalign -v 4 \
          ./app/build/outputs/apk/nonRoot/release/app-nonRoot-release-debugsigned.apk \
          ./app/build/outputs/apk/nonRoot/release/app-nonRoot-release.apk

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: moonlight-android.apk
          path: ./app/build/outputs/apk/nonRoot/release/app-nonRoot-release.apk

      # - name: Create Release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "./app/build/outputs/apk/nonRoot/release/app-nonRoot-release.apk"
